=== tjwoodall/individuals-capital-gains-income-api/resources/public/api/conf/3.0/schemas/capital_gains_other_create_amend/def3/request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "TY 2026-27 onwards {{#unless (releasedInProduction 'r22_cgt_docs')}}[Test Only]{{/unless}}",
  "type": "object",
  "properties": {
    "cryptoassets": {
      "$ref": "../../capital_gains_other_definitions.json#/definitions/cryptoassets2627"
    },
    "otherGains": {
      "$ref": "../../capital_gains_other_definitions.json#/definitions/otherGains2627"
    },
    "unlistedShares": {
      "$ref": "../../capital_gains_other_definitions.json#/definitions/unlistedShares2627"
    },
    "gainExcludedIndexedSecurities": {
      "$ref": "../../capital_gains_other_definitions.json#/definitions/gainExcludedIndexedSecurities"
    },
    "qualifyingAssetHoldingCompany": {
      "$ref": "../../capital_gains_other_definitions.json#/definitions/qualifyingAssetHoldingCompany"
    },
    "losses": {
      "$ref": "../../capital_gains_other_definitions.json#/definitions/losses2526"
    },
    "adjustments": {
      "$ref": "../../capital_gains_other_definitions.json#/definitions/adjustments2627"
    },
    "lifetimeAllowance": {
      "$ref": "../../capital_gains_other_definitions.json#/definitions/lifetimeAllowance"
    }
  }
}

=== tjwoodall/individuals-capital-gains-income-api/resources/public/api/conf/3.0/examples/capital_gains_other_create_amend/def3/request.json
{
  "cryptoassets": [
    {
      "numberOfDisposals": 1,
      "assetDescription": "description string",
      "tokenName": "Name of token",
      "acquisitionDate": "2026-08-04",
      "disposalDate": "2026-09-04",
      "disposalProceeds": 99999999999.99,
      "allowableCosts": 99999999999.99,
      "gainsWithBadr": 99999999999.99,
      "gainsBeforeLosses": 99999999999.99,
      "losses": 99999999999.99,
      "claimOrElectionCodes": ["GHO", "INC"],
      "amountOfNetGain": 99999999999.99,
      "rttTaxPaid": 99999999999.99
    }
  ],
  "otherGains": [
    {
      "assetType": "other-property",
      "numberOfDisposals": 1,
      "assetDescription": "example of this asset",
      "companyName": "Bob the Builder",
      "companyRegistrationNumber": "11111111",
      "acquisitionDate": "2026-04-07",
      "disposalDate": "2026-07-10",
      "disposalProceeds": 99999999999.99,
      "allowableCosts": 99999999999.99,
      "gainsWithBadr": 99999999999.99,
      "gainsWithInv": 99999999999.99,
      "gainsBeforeLosses": 99999999999.99,
      "losses": 99999999999.99,
      "claimOrElectionCodes": ["PRR", "INC"],
      "amountOfNetGain": 99999999999.99,
      "rttTaxPaid": 99999999999.99
    }
  ],
  "unlistedShares": [
    {
      "numberOfDisposals": 1,
      "assetDescription": "My asset",
      "companyName": "Bob the Builder",
      "companyRegistrationNumber": "11111111",
      "acquisitionDate": "2026-04-10",
      "disposalDate": "2026-04-12",
      "disposalProceeds": 99999999999.99,
      "allowableCosts": 99999999999.99,
      "gainsWithBadr": 99999999999.99,
      "gainsWithInv": 99999999999.99,
      "gainsBeforeLosses": 99999999999.99,
      "losses": 99999999999.99,
      "claimOrElectionCodes": ["GHO", "INC"],
      "gainsReportedOnRtt": 99999999999.99,
      "gainsExceedingLifetimeLimit": 99999999999.99,
      "gainsUnderSeis": 99999999999.99,
      "lossUsedAgainstGeneralIncome": 99999999999.99,
      "eisOrSeisReliefDueCurrentYear": 99999999999.99,
      "lossesUsedAgainstGeneralIncomePreviousYear": 99999999999.99,
      "eisOrSeisReliefDuePreviousYear": 99999999999.99,
      "rttTaxPaid": 99999999999.99
    }
  ],
  "gainExcludedIndexedSecurities": {
    "gainsFromExcludedSecurities": 99999999999.99
  },
  "qualifyingAssetHoldingCompany": {
    "gainsFromQahcBeforeLosses": 99999999999.99,
    "lossesFromQahc": 99999999999.99
  },
  "losses": {
    "broughtForwardLossesUsedInCurrentYear": 99999999999.99,
    "setAgainstInYearGains": 99999999999.99,
    "setAgainstEarlierYear": 99999999999.99,
    "lossesToCarryForward": 99999999999.99
  },
  "adjustments": {
    "adjustmentAmount": -99999999999.99
  },
  "lifetimeAllowance": {
    "lifetimeAllowanceBadr": 99999999999.99,
    "lifetimeAllowanceInv": 99999999999.99
  }
}
